server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: image
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: swarm_service
      # MinIO-specific labels
      - source_labels: [__meta_docker_container_name]
        regex: beacon-minio(\d+)
        target_label: node
        replacement: minio${1}
      - source_labels: [__meta_docker_container_name]
        regex: beacon-minio.*
        target_label: service
        replacement: minio
    pipeline_stages:
      - docker: {}
