global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets:
        - 'minio1:9000'
        - 'minio2:9000'
        - 'minio3:9000'

  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'dns-probe'
    metrics_path: /probe
    params:
      module: [dns_technitium]
    static_configs:
      - targets:
        - 'technitium-dns:53'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['infra-traefik:9100']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'http://nginx/healthz'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - 'infra-keycloak-db:5432'
        - 'beacon-redis:6379'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['infra-keycloak:9000']

  - job_name: 'keycloak-db'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'beacon-vectordb-postgres'
    static_configs:
      - targets: ['beacon-vectordb-exporter:9187']
